//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GopYCauHoi
    {
        public long GopYCauHoiId { get; set; }
        public string SoBienNhan { get; set; }
        public Nullable<long> CauHoiId { get; set; }
        public string NoiDungGopY { get; set; }
        public Nullable<long> TieuChiId { get; set; }
    }
}
