//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaDanhGia_CH_Mo
    {
        public long ID { get; set; }
        public Nullable<long> DanhGiaID { get; set; }
        public Nullable<long> CauHoiID { get; set; }
        public string KetQua { get; set; }
    }
}
