//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhXuLy
    {
        public int ID { get; set; }
        public string HoSoID { get; set; }
        public Nullable<int> DonViID { get; set; }
        public Nullable<int> NguoiXuLyID { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string ThoiHanXuLy { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
        public string TinhTrang { get; set; }
        public string KetQua { get; set; }
        public string NguoiXuLy { get; set; }
    }
}
