//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;

    public partial class Thang_BaoCao
    {
        public long ID { get; set; }
        public Nullable<int> QuyID { get; set; }
        public Nullable<int> NamID { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<System.DateTime> NgayDauThang { get; set; }
        public Nullable<System.DateTime> NgayCuoiThang { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdUserID { get; set; }
        public Nullable<System.DateTime> LastUpdDate { get; set; }
    }
}
