//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;

    public partial class TK_DonVi_Quy
    {
        public int ID { get; set; }
        public Nullable<int> DonViID { get; set; }
        public string TenDonVi { get; set; }
        public int NamID { get; set; }
        public Nullable<int> QuiID { get; set; }
        public string KeQuaDanhGia { get; set; }
    }
}
