//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_TongHop_Thang
    {
        public int ID { get; set; }
        public Nullable<int> DonViID { get; set; }
        public Nullable<int> ThangID { get; set; }
        public Nullable<int> NamID { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<decimal> HaiLong { get; set; }
        public Nullable<decimal> KhongHaiLong { get; set; }
        public Nullable<decimal> BinhThuong { get; set; }
    }
}
