//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;

    public partial class Tuan_BaoCao
    {
        public long ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
        public Nullable<System.DateTime> StartOfWeek { get; set; }
        public Nullable<System.DateTime> EndOfWeek { get; set; }
    }
}
