//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInRoles
    {
        public int ID { get; set; }
    
        public virtual Memberships Memberships { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
