//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBCC.SearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.IWebSearch")]
    public interface IWebSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/WebSearch", ReplyAction="http://tempuri.org/IWebSearch/WebSearchResponse")]
        System.Data.DataSet WebSearch(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/WebSearch", ReplyAction="http://tempuri.org/IWebSearch/WebSearchResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebSearchAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/DoNothing", ReplyAction="http://tempuri.org/IWebSearch/DoNothingResponse")]
        string DoNothing(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/DoNothing", ReplyAction="http://tempuri.org/IWebSearch/DoNothingResponse")]
        System.Threading.Tasks.Task<string> DoNothingAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/ServiceManager", ReplyAction="http://tempuri.org/IWebSearch/ServiceManagerResponse")]
        System.Data.DataSet ServiceManager(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/ServiceManager", ReplyAction="http://tempuri.org/IWebSearch/ServiceManagerResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ServiceManagerAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SearchFiles", ReplyAction="http://tempuri.org/IWebSearch/SearchFilesResponse")]
        CBCC.SearchService.SearchFilesResponse SearchFiles(CBCC.SearchService.SearchFilesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SearchFiles", ReplyAction="http://tempuri.org/IWebSearch/SearchFilesResponse")]
        System.Threading.Tasks.Task<CBCC.SearchService.SearchFilesResponse> SearchFilesAsync(CBCC.SearchService.SearchFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SelectRegions", ReplyAction="http://tempuri.org/IWebSearch/SelectRegionsResponse")]
        CBCC.SearchService.SelectRegionsResponse SelectRegions(CBCC.SearchService.SelectRegionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SelectRegions", ReplyAction="http://tempuri.org/IWebSearch/SelectRegionsResponse")]
        System.Threading.Tasks.Task<CBCC.SearchService.SelectRegionsResponse> SelectRegionsAsync(CBCC.SearchService.SelectRegionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_Active", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_ActiveResponse")]
        void SCOPE_Active(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_Active", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_ActiveResponse")]
        System.Threading.Tasks.Task SCOPE_ActiveAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_GetListByRegion", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_GetListByRegionResponse")]
        System.Data.DataSet SCOPE_GetListByRegion(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_GetListByRegion", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_GetListByRegionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SCOPE_GetListByRegionAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_GetScopeList", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_GetScopeListResponse")]
        System.Data.DataSet SCOPE_GetScopeList(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSearch/SCOPE_GetScopeList", ReplyAction="http://tempuri.org/IWebSearch/SCOPE_GetScopeListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SCOPE_GetScopeListAsync(System.Collections.Generic.Dictionary<object, object> datas);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<object, object> datas;
        
        public SearchFilesRequest() {
        }
        
        public SearchFilesRequest(System.Collections.Generic.Dictionary<object, object> datas) {
            this.datas = datas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet SearchFilesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Totalrows;
        
        public SearchFilesResponse() {
        }
        
        public SearchFilesResponse(System.Data.DataSet SearchFilesResult, int Totalrows) {
            this.SearchFilesResult = SearchFilesResult;
            this.Totalrows = Totalrows;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectRegions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectRegionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int PortalID;
        
        public SelectRegionsRequest() {
        }
        
        public SelectRegionsRequest(int PortalID) {
            this.PortalID = PortalID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectRegionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet SelectRegionsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DefaultRegCode;
        
        public SelectRegionsResponse() {
        }
        
        public SelectRegionsResponse(System.Data.DataSet SelectRegionsResult, string DefaultRegCode) {
            this.SelectRegionsResult = SelectRegionsResult;
            this.DefaultRegCode = DefaultRegCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebSearchChannel : CBCC.SearchService.IWebSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSearchClient : System.ServiceModel.ClientBase<CBCC.SearchService.IWebSearch>, CBCC.SearchService.IWebSearch {
        
        public WebSearchClient() {
        }
        
        public WebSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebSearch(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.WebSearch(datas);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebSearchAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.WebSearchAsync(datas);
        }
        
        public string DoNothing(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.DoNothing(datas);
        }
        
        public System.Threading.Tasks.Task<string> DoNothingAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.DoNothingAsync(datas);
        }
        
        public System.Data.DataSet ServiceManager(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.ServiceManager(datas);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ServiceManagerAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.ServiceManagerAsync(datas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CBCC.SearchService.SearchFilesResponse CBCC.SearchService.IWebSearch.SearchFiles(CBCC.SearchService.SearchFilesRequest request) {
            return base.Channel.SearchFiles(request);
        }
        
        public System.Data.DataSet SearchFiles(System.Collections.Generic.Dictionary<object, object> datas, out int Totalrows) {
            CBCC.SearchService.SearchFilesRequest inValue = new CBCC.SearchService.SearchFilesRequest();
            inValue.datas = datas;
            CBCC.SearchService.SearchFilesResponse retVal = ((CBCC.SearchService.IWebSearch)(this)).SearchFiles(inValue);
            Totalrows = retVal.Totalrows;
            return retVal.SearchFilesResult;
        }
        
        public System.Threading.Tasks.Task<CBCC.SearchService.SearchFilesResponse> SearchFilesAsync(CBCC.SearchService.SearchFilesRequest request) {
            return base.Channel.SearchFilesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CBCC.SearchService.SelectRegionsResponse CBCC.SearchService.IWebSearch.SelectRegions(CBCC.SearchService.SelectRegionsRequest request) {
            return base.Channel.SelectRegions(request);
        }
        
        public System.Data.DataSet SelectRegions(int PortalID, out string DefaultRegCode) {
            CBCC.SearchService.SelectRegionsRequest inValue = new CBCC.SearchService.SelectRegionsRequest();
            inValue.PortalID = PortalID;
            CBCC.SearchService.SelectRegionsResponse retVal = ((CBCC.SearchService.IWebSearch)(this)).SelectRegions(inValue);
            DefaultRegCode = retVal.DefaultRegCode;
            return retVal.SelectRegionsResult;
        }
        
        public System.Threading.Tasks.Task<CBCC.SearchService.SelectRegionsResponse> SelectRegionsAsync(CBCC.SearchService.SelectRegionsRequest request) {
            return base.Channel.SelectRegionsAsync(request);
        }
        
        public void SCOPE_Active(System.Collections.Generic.Dictionary<object, object> datas) {
            base.Channel.SCOPE_Active(datas);
        }
        
        public System.Threading.Tasks.Task SCOPE_ActiveAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SCOPE_ActiveAsync(datas);
        }
        
        public System.Data.DataSet SCOPE_GetListByRegion(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SCOPE_GetListByRegion(datas);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SCOPE_GetListByRegionAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SCOPE_GetListByRegionAsync(datas);
        }
        
        public System.Data.DataSet SCOPE_GetScopeList(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SCOPE_GetScopeList(datas);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SCOPE_GetScopeListAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SCOPE_GetScopeListAsync(datas);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.ISMSSearch")]
    public interface ISMSSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SMSSearch", ReplyAction="http://tempuri.org/ISMSSearch/SMSSearchResponse")]
        string SMSSearch(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SMSSearch", ReplyAction="http://tempuri.org/ISMSSearch/SMSSearchResponse")]
        System.Threading.Tasks.Task<string> SMSSearchAsync(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SaveSMSIN", ReplyAction="http://tempuri.org/ISMSSearch/SaveSMSINResponse")]
        string SaveSMSIN(string p_Sender, string p_FullMessage, string p_Prefix, string p_Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SaveSMSIN", ReplyAction="http://tempuri.org/ISMSSearch/SaveSMSINResponse")]
        System.Threading.Tasks.Task<string> SaveSMSINAsync(string p_Sender, string p_FullMessage, string p_Prefix, string p_Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SaveSMSOUT", ReplyAction="http://tempuri.org/ISMSSearch/SaveSMSOUTResponse")]
        void SaveSMSOUT(string p_Sender, string p_Message, string p_SMSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSearch/SaveSMSOUT", ReplyAction="http://tempuri.org/ISMSSearch/SaveSMSOUTResponse")]
        System.Threading.Tasks.Task SaveSMSOUTAsync(string p_Sender, string p_Message, string p_SMSID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSSearchChannel : CBCC.SearchService.ISMSSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSearchClient : System.ServiceModel.ClientBase<CBCC.SearchService.ISMSSearch>, CBCC.SearchService.ISMSSearch {
        
        public SMSSearchClient() {
        }
        
        public SMSSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SMSSearch(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SMSSearch(datas);
        }
        
        public System.Threading.Tasks.Task<string> SMSSearchAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.SMSSearchAsync(datas);
        }
        
        public string SaveSMSIN(string p_Sender, string p_FullMessage, string p_Prefix, string p_Message) {
            return base.Channel.SaveSMSIN(p_Sender, p_FullMessage, p_Prefix, p_Message);
        }
        
        public System.Threading.Tasks.Task<string> SaveSMSINAsync(string p_Sender, string p_FullMessage, string p_Prefix, string p_Message) {
            return base.Channel.SaveSMSINAsync(p_Sender, p_FullMessage, p_Prefix, p_Message);
        }
        
        public void SaveSMSOUT(string p_Sender, string p_Message, string p_SMSID) {
            base.Channel.SaveSMSOUT(p_Sender, p_Message, p_SMSID);
        }
        
        public System.Threading.Tasks.Task SaveSMSOUTAsync(string p_Sender, string p_Message, string p_SMSID) {
            return base.Channel.SaveSMSOUTAsync(p_Sender, p_Message, p_SMSID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.IVoiceSearch")]
    public interface IVoiceSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoiceSearch/VoiceSearch", ReplyAction="http://tempuri.org/IVoiceSearch/VoiceSearchResponse")]
        string VoiceSearch(System.Collections.Generic.Dictionary<object, object> datas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoiceSearch/VoiceSearch", ReplyAction="http://tempuri.org/IVoiceSearch/VoiceSearchResponse")]
        System.Threading.Tasks.Task<string> VoiceSearchAsync(System.Collections.Generic.Dictionary<object, object> datas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoiceSearchChannel : CBCC.SearchService.IVoiceSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceSearchClient : System.ServiceModel.ClientBase<CBCC.SearchService.IVoiceSearch>, CBCC.SearchService.IVoiceSearch {
        
        public VoiceSearchClient() {
        }
        
        public VoiceSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VoiceSearch(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.VoiceSearch(datas);
        }
        
        public System.Threading.Tasks.Task<string> VoiceSearchAsync(System.Collections.Generic.Dictionary<object, object> datas) {
            return base.Channel.VoiceSearchAsync(datas);
        }
    }
}
