//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class CauTraLoiExtend : CauTraLoi
    {
        public CauTraLoiExtend()
        {
            this.TieuChiCauTraLois = new HashSet<TieuChiCauTraLoi>();;
            this.ListGiaTri = new List<SelectListItem>();

            var item = new SelectListItem { Text = "--- Chọn ---", Value = string.Empty };
            ListGiaTri.Insert(0, item);

            item = new SelectListItem { Text = "Không hài lòng", Value = "-1" };
            ListGiaTri.Insert(1, item);

            item = new SelectListItem { Text = "Bình thường", Value = "0" };
            ListGiaTri.Insert(2, item);

            item = new SelectListItem { Text = "Hài lòng", Value = "1" };
            ListGiaTri.Insert(3, item);
        }

        public List<SelectListItem> ListGiaTri { get; set; }
       
    }
}
