//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{

    public partial class ThongKe 
    { 
        public int? DonViID { get; set; }
        public string TenDonVi { get; set; }
        public string KetQuaDanhGia { get; set; }
        public double? HaiLong { get; set; }
        public double? KhongHaiLong { get; set; }
        public double? BinhThuong { get; set; }
    }
}
