//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Entities
{

    public partial class ThongKe 
    { 
        public int? DonViID { get; set; }
        public string MaDonVi { get; set; }
        public string MaLienThong { get; set; }
        public string TenDonVi { get; set; }
        public string KetQuaDanhGia { get; set; }
        public double HaiLong { get; set; }
        public double KhongHaiLong { get; set; }
        public double BinhThuong { get; set; }
        public string SCHaiLong { get; set; }
        public string SCKhongHaiLong { get; set; }
        public string SCBinhThuong { get; set; }
        public int Soluot { get; set; }
        public int IDCau { get; set; }
        public long DanhGiaID { get; set; }
        public string MonthYear { get; set; }
        public string SoBienNhan { get; set; }
        public string Question { get; set; }
        public string NDGopY { get; set; }
        public string NoiDungGopY { get; set; }
        public string TenTieuChi { get; set; }
        public string ChiTiet { get; set; }
        public string ChapNhanDuoc { get; set; }
        public string KhoSuDung { get; set; }
        public string Khac { get; set; }
        public int rowChapNhan { get; set; }
        public int rowKhoSuDung { get; set; }
        public int rowKhac { get; set; }
        public int Total { get; set; }
    }
}
